import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { createApp } from 'vue';
import App from './App.vue';
import router from '@/router';
// import focus from '@/directives/focus';
// import fucPlugins from './plugins/fun';
// import objPlugins from './plugins/obj.js';
// import person from './plugins/person.js';
// import globalComponents from '@/plugins/global-components';
import globalDirectives from '@/plugins/global-directives';
import dayjs from '@/plugins/dayjs';
const app = createApp(App);
// app.use(globalComponents);
// app.use(fucPlugins);
// app.use(objPlugins, { name: '이름' });
// app.use(person, { name: '홍길동' });
app.use(router);
app.use(globalDirectives);
app.use(dayjs);
// app.directive('focus', focus);
app.mount('#app');
import 'bootstrap/dist/js/bootstrap.js';

// console.log('mode : ', import.meta.env.MODE);
// console.log('BASE_URL : ', import.meta.env.BASE_URL);
// console.log('PROD : ', import.meta.env.PROD);
// console.log('DEV : ', import.meta.env.DEV);
